name: .NET

on: [pull_request]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
    - name: Hello message
      run: echo "Hello world"
  build:
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
      run: dotnet build
  test:
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
      run: dotnet test
  publish:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
      run: dotnet publish